p: &p
  type: http
  interval: 86400
  health-check: { enable: true, url: https://www.gstatic.com/generate_204, interval: 1800 }
  proxy: Update
  header: { User-Agent: ["ClashMetaForAndroid/2.11.32.Meta"] }

proxy-providers:
  <provider_name>:
    <<: *p
    path: proxies/1.yaml
    url: <provider_url>

  <one_time_provider_name>:
    <<: *p
    interval: 0
    override:
      additional-suffix: ""
      override-expr:
        - '(select(.server == "<original_server>") | .server) = "<mapped_server>"'
    path: proxies/2.yaml
    url: <provider_url>

mixed-port: 7890
ipv6: false
allow-lan: true
unified-delay: true
tcp-concurrent: true
log-level: silent
find-process-mode: off

external-controller: 0.0.0.0:9090
external-ui: ui
external-ui-url: https://github.com/Zephyruso/zashboard/releases/latest/download/dist.zip
secret: <secret>

profile:
  store-selected: true
  store-fake-ip: true

sniffer:
  enable: true
  force-dns-mapping: true
  parse-pure-ip: true
  override-destination: true
  sniff:
    HTTP:
      ports: [80, 8080-8880]
    TLS:
      ports: [443, 5228, 8443]
    QUIC:
      ports: [443, 8443]
  skip-domain:
    - "Mijia Cloud"
    - "+.push.apple.com"

tun:
  enable: true
  stack: mixed
  device: Meta
  dns-hijack:
    - any:53
    - tcp://any:53
  auto-route: true
  strict-route: true
  auto-redirect: true
  auto-detect-interface: true

hosts:
  dns.alidns.com: [223.5.5.5, 223.6.6.6]
  doh.pub: [1.12.12.12, 120.53.53.53]
  cloudflare-dns.com: [1.1.1.1, 1.0.0.1]
  dns.google: [8.8.8.8, 8.8.4.4]

dns:
  enable: true
  cache-algorithm: arc
  ipv6: false
  use-hosts: true
  listen: 0.0.0.0:1053
  enhanced-mode: fake-ip
  fake-ip-range: 28.0.0.1/8
  fake-ip-filter-mode: rule
  fake-ip-filter:
    - RULE-SET,custom_direct,real-ip
    - RULE-SET,custom_proxy,fake-ip
    - RULE-SET,ads_domain,fake-ip
    - RULE-SET,private_domain,real-ip
    - RULE-SET,fcm_domain,real-ip
    - RULE-SET,geolocation_not_cn,fake-ip
    - RULE-SET,cn_domain,real-ip
    - MATCH,fake-ip
  default-nameserver:
    - quic://223.5.5.5
    - https://223.6.6.6/dns-query
    # - 119.29.29.29
  proxy-server-nameserver: &direct_dns
    - https://dns.alidns.com/dns-query#h3=true
    - https://doh.pub/dns-query
  proxy-server-nameserver-policy:
  nameserver-policy:
    "rule-set:private_domain,fcm_domain,cn_domain,custom_direct": *direct_dns
  nameserver:
    - https://cloudflare-dns.com/dns-query#Proxy
    - https://dns.google/dns-query#Proxy

proxies:
  - name: Exit 1
    type: vless
    server: <server>
    port: 443
    udp: true
    dialer-proxy: Relay
    smux: { enabled: false }
    tls: false
    uuid: <uuid>
    flow: xtls-rprx-vision
    packet-encoding: xudp
    encryption: "mlkem768x25519plus.xorpub.0rtt.<x25519_password>"
    network: tcp

proxy-groups:
  - name: Proxy
    type: select
    proxies: [Exit, US, JP, SG, TW, HK, Other, REJECT, DIRECT]
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Rocket.png

  - name: Exit
    type: select
    include-all-proxies: true
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Area.png

  - name: Relay
    type: select
    proxies: [US, JP, SG, TW, HK, Other]
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Stack.png

  - name: US
    type: select
    include-all-providers: true
    filter: "(?i)(🇺🇸|美国)"
    empty-fallback: REJECT
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/United_States.png

  - name: Special
    type: select
    proxies: [PASS, REJECT, US, JP, SG, TW, HK, Other]
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Lab.png

  - name: Update
    type: select
    proxies: [DIRECT, Proxy]
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Round_Robin.png

  - name: Ads
    type: select
    proxies: [REJECT, PASS, REJECT-DROP]
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Advertising.png

  - name: QUIC
    type: select
    proxies: [REJECT, PASS, REJECT-DROP]
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/ForeignMedia.png

  - name: NSFW
    type: select
    proxies: [JP, TW, HK, SG, US, Other, DIRECT]
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Lock.png

  - name: TikTok
    type: select
    proxies: [Proxy, US, JP, SG, TW, HK, Other, DIRECT]
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/TikTok.png

  - name: Google
    type: select
    proxies: [Proxy, US, JP, SG, TW, HK, Other, DIRECT]
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Google_Search.png

  - name: FCM
    type: select
    proxies: [DIRECT, Proxy]
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Mail.png

  - name: Bilibili
    type: select
    proxies: [DIRECT, TW, HK]
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/bilibili.png

  - name: Steam
    type: select
    proxies: [DIRECT, US, JP, SG, TW, HK, Other]
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Game.png

  - name: Microsoft
    type: select
    proxies: [Proxy, DIRECT, US, JP, SG, TW, HK, Other]
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Microsoft.png

  - name: Apple
    type: select
    proxies: [Proxy, DIRECT, US, JP, SG, TW, HK, Other]
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Apple.png

  - name: Final
    type: select
    proxies: [Proxy, DIRECT, US, JP, SG, TW, HK, Other]
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Final.png

  - name: JP
    type: select
    include-all-providers: true
    filter: "(?i)(🇯🇵|日本)"
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Japan.png

  - name: SG
    type: select
    include-all-providers: true
    filter: "(?i)(🇸🇬|新加坡)"
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Singapore.png

  - name: TW
    type: select
    include-all-providers: true
    filter: "(?i)(🇹🇼|🇨🇳|台湾)"
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Taiwan.png

  - name: HK
    type: select
    include-all-providers: true
    filter: "(?i)(🇭🇰|香港)"
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Hong_Kong.png

  - name: Other
    type: select
    include-all-providers: true
    filter: "(?i)^(?!.*(?:🇺🇸|🇯🇵|🇸🇬|🇹🇼|🇨🇳|🇭🇰|美国|日本|新加坡|台湾|香港)).*"
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Global.png

  - name: GLOBAL
    type: select
    proxies:
      - Proxy
      - DIRECT
      - REJECT
      - Exit
      - Relay
      - US
      - Special
      - Update
      - Ads
      - QUIC
      - NSFW
      - TikTok
      - Google
      - FCM
      - Bilibili
      - Steam
      - Microsoft
      - Apple
      - Final
      - JP
      - SG
      - TW
      - HK
      - Other

rule-anchor:
  classical: &classical
    type: http
    behavior: classical
    format: text
    interval: 86400
    proxy: Proxy
    # header: { Authorization: [<authorization>] }
  ip: &ip { type: http, behavior: ipcidr, format: mrs, interval: 86400, proxy: Proxy }
  domain: &domain { type: http, behavior: domain, format: mrs, interval: 86400, proxy: Proxy }

rule-providers:
  special_address:
    <<: *classical
    path: rules/special.list
    url: <special_address_url>

  custom_direct:
    <<: *classical
    path: rules/direct.list
    url: <custom_direct_url>
  custom_proxy:
    <<: *classical
    path: rules/proxy.list
    url: <custom_proxy_url>

  ads_domain:
    <<: *domain
    path: rules/external/ads_domain.mrs
    url: https://raw.githubusercontent.com/TG-Twilight/AWAvenue-Ads-Rule/main/Filters/AWAvenue-Ads-Rule-Clash.mrs

  private_domain:
    <<: *domain
    path: rules/external/private_domain.mrs
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/private.mrs
  private_ip:
    <<: *ip
    path: rules/external/private_ip.mrs
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/private.mrs

  bilibili_domain:
    <<: *domain
    path: rules/external/bilibili_domain.mrs
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/bilibili.mrs
  bilibili_ip:
    <<: *ip
    path: rules/external/bilibili_ip.mrs
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo-lite/geoip/bilibili.mrs

  tiktok_domain:
    <<: *domain
    path: rules/external/tiktok_domain.mrs
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/tiktok.mrs

  steam_domain:
    <<: *domain
    path: rules/external/steam_domain.mrs
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/steam.mrs

  fcm_domain:
    <<: *domain
    path: rules/external/fcm_domain.mrs
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/googlefcm.mrs

  google_domain:
    <<: *domain
    path: rules/external/google_domain.mrs
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/google.mrs
  google_ip:
    <<: *ip
    path: rules/external/google_ip.mrs
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/google.mrs

  microsoft_domain:
    <<: *domain
    path: rules/external/microsoft_domain.mrs
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/microsoft.mrs

  apple_domain:
    <<: *domain
    path: rules/external/apple_domain.mrs
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/apple.mrs
  apple_ip:
    <<: *ip
    path: rules/external/apple_ip.mrs
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo-lite/geoip/apple.mrs

  porn_domain:
    <<: *domain
    path: rules/external/porn_domain.mrs
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/category-porn.mrs

  geolocation_not_cn:
    <<: *domain
    path: rules/external/geolocation_not_cn.mrs
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/geolocation-!cn.mrs
  cn_domain:
    <<: *domain
    path: rules/external/cn_domain.mrs
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/cn.mrs
  cn_ip:
    <<: *ip
    path: rules/external/cn_ip.mrs
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/cn.mrs

rules:
  - AND,((NETWORK,UDP),(DST-PORT,443),(NOT,((OR,((RULE-SET,cn_domain),(RULE-SET,cn_ip,no-resolve),(RULE-SET,private_domain),(RULE-SET,private_ip,no-resolve),(RULE-SET,custom_direct,no-resolve)))))),QUIC
  - RULE-SET,special_address,Special,no-resolve
  - RULE-SET,custom_direct,DIRECT,no-resolve
  - RULE-SET,custom_proxy,Proxy,no-resolve
  - RULE-SET,ads_domain,Ads
  - RULE-SET,private_domain,DIRECT
  - RULE-SET,bilibili_domain,Bilibili
  - RULE-SET,tiktok_domain,TikTok
  - RULE-SET,steam_domain,Steam
  - RULE-SET,fcm_domain,FCM
  - RULE-SET,google_domain,Google
  - DOMAIN-SUFFIX,dl.delivery.mp.microsoft.com,DIRECT
  - DOMAIN-SUFFIX,windowsupdate.com,DIRECT
  - RULE-SET,microsoft_domain,Microsoft
  - RULE-SET,apple_domain,Apple
  - RULE-SET,porn_domain,NSFW
  - RULE-SET,geolocation_not_cn,Proxy

  - RULE-SET,private_ip,DIRECT
  - RULE-SET,bilibili_ip,Bilibili
  - RULE-SET,google_ip,Google
  - RULE-SET,apple_ip,Apple
  - RULE-SET,cn_domain,DIRECT
  - RULE-SET,cn_ip,DIRECT
  - MATCH,Final
