p: &p
  type: http
  health-check:
    enable: true
    url: https://www.gstatic.com/generate_204
    interval: 1800
  proxy: 订阅更新

proxy-providers:
  __PROVIDER_NAME__:
    <<: *p
    interval: 86400
    path: ./proxy_providers/1.yaml
    url: "__PROVIDER_URL__"

  __ONE_TIME_PROVIDER_NAME__:
    <<: *p
    path: ./proxy_providers/2.yaml
    url: "__ONE_TIME_PROVIDER_URL__"

mixed-port: 7890
ipv6: false
allow-lan: true
unified-delay: true
tcp-concurrent: true
log-level: silent
find-process-mode: off

external-controller: 0.0.0.0:9090
external-ui: WebUI
external-ui-url: "https://github.com/Zephyruso/zashboard/releases/latest/download/dist.zip"
secret: "__YOUR_SECRET__"

profile:
  store-selected: true
  store-fake-ip: true

sniffer:
  enable: true
  force-dns-mapping: true
  parse-pure-ip: true
  override-destination: true
  sniff:
    HTTP:
      ports: [80, 8080-8880]
    TLS:
      ports: [443, 5228, 8443]
    QUIC:
      ports: [443, 8443]
  skip-domain:
    - "Mijia Cloud"
    - "+.push.apple.com"

tun:
  enable: true
  stack: system
  device: Meta
  dns-hijack:
    - any:53
    - tcp://any:53
  auto-route: true
  strict-route: true
  auto-redirect: true
  auto-detect-interface: true

hosts:
  dns.alidns.com: [223.5.5.5, 223.6.6.6]
  doh.pub: [1.12.12.12, 120.53.53.53]
  cloudflare-dns.com: [1.1.1.1, 1.0.0.1]
  dns.google: [8.8.8.8, 8.8.4.4]

dns:
  enable: true
  cache-algorithm: arc
  ipv6: false
  listen: 0.0.0.0:1053
  enhanced-mode: fake-ip
  fake-ip-range: 28.0.0.1/8
  fake-ip-filter:
    - "rule-set:private_domain,fcm_domain,cn_domain,custom_direct"
  proxy-server-nameserver: &direct_dns
    - https://dns.alidns.com/dns-query#DIRECT&h3=true
    - https://doh.pub/dns-query#DIRECT&h3=false
  nameserver-policy:
    "rule-set:private_domain,fcm_domain,cn_domain,custom_direct": *direct_dns
  nameserver:
    - https://cloudflare-dns.com/dns-query#节点选择
    - https://dns.google/dns-query#节点选择

proxy-groups:
  - name: 节点选择
    type: select
    proxies:
      - 美国节点
      - 日本节点
      - 狮城节点
      - 台湾节点
      - 香港节点
      - 其余节点
      - REJECT
      - DIRECT
    icon: "https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Rocket.png"

  - name: 美国节点
    type: select
    include-all-providers: true
    filter: "(?i)(🇺🇸|美国)"
    icon: "https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/United_States.png"

  - name: 特殊地址
    type: select
    proxies:
      - PASS
      - DIRECT
      - REJECT
    include-all: true
    icon: "https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Lab.png"

  - name: 订阅更新
    type: select
    proxies:
      - 节点选择
      - DIRECT
    icon: "https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Round_Robin.png"

  - name: 广告拦截
    type: select
    proxies:
      - REJECT
      - PASS
      - REJECT-DROP
    icon: "https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Advertising.png"

  - name: QUIC
    type: select
    proxies:
      - REJECT
      - PASS
      - REJECT-DROP
    icon: "https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/ForeignMedia.png"

  - name: PORN
    type: select
    proxies:
      - 日本节点
      - 台湾节点
      - 香港节点
      - 狮城节点
      - 美国节点
      - 其余节点
      - DIRECT
    icon: "https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Pornhub.png"

  - name: TikTok
    type: select
    proxies:
      - 节点选择
      - 美国节点
      - 日本节点
      - 狮城节点
      - 台湾节点
      - 香港节点
      - 其余节点
      - DIRECT
    icon: "https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/TikTok.png"

  - name: Google
    type: select
    proxies:
      - 节点选择
      - 美国节点
      - 日本节点
      - 狮城节点
      - 台湾节点
      - 香港节点
      - 其余节点
      - DIRECT
    icon: "https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Google_Search.png"

  - name: 谷歌FCM
    type: select
    proxies:
      - DIRECT
      - 节点选择
    icon: "https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Mail.png"

  - name: 哔哩哔哩
    type: select
    proxies:
      - DIRECT
      - 台湾节点
      - 香港节点
    icon: "https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/bilibili.png"

  - name: 游戏平台
    type: select
    proxies:
      - DIRECT
      - 美国节点
      - 日本节点
      - 狮城节点
      - 台湾节点
      - 香港节点
      - 其余节点
    icon: "https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Game.png"

  - name: 微软服务
    type: select
    proxies:
      - 节点选择
      - DIRECT
      - 美国节点
      - 日本节点
      - 狮城节点
      - 台湾节点
      - 香港节点
      - 其余节点
    icon: "https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Microsoft.png"

  - name: 苹果服务
    type: select
    proxies:
      - 节点选择
      - DIRECT
      - 美国节点
      - 日本节点
      - 狮城节点
      - 台湾节点
      - 香港节点
      - 其余节点
    icon: "https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Apple.png"

  - name: 漏网之鱼
    type: select
    proxies:
      - 节点选择
      - DIRECT
      - 美国节点
      - 日本节点
      - 狮城节点
      - 台湾节点
      - 香港节点
      - 其余节点
    icon: "https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Final.png"

  - name: 日本节点
    type: select
    include-all-providers: true
    filter: "(?i)(🇯🇵|日本)"
    icon: "https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Japan.png"

  - name: 狮城节点
    type: select
    include-all-providers: true
    filter: "(?i)(🇸🇬|新加坡)"
    icon: "https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Singapore.png"

  - name: 台湾节点
    type: select
    include-all-providers: true
    filter: "(?i)(🇹🇼|🇨🇳|台湾)"
    icon: "https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Taiwan.png"

  - name: 香港节点
    type: select
    include-all-providers: true
    filter: "(?i)(🇭🇰|香港)"
    icon: "https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Hong_Kong.png"

  - name: 其余节点
    type: select
    include-all-providers: true
    filter: "(?i)^(?!.*(?:🇺🇸|🇯🇵|🇸🇬|🇹🇼|🇨🇳|🇭🇰|美国|日本|新加坡|台湾|香港)).*"
    icon: "https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Global.png"

  - name: GLOBAL
    type: select
    proxies:
      - 节点选择
      - DIRECT
      - REJECT
      - 美国节点
      - 特殊地址
      - 订阅更新
      - 广告拦截
      - QUIC
      - PORN
      - TikTok
      - Google
      - 谷歌FCM
      - 哔哩哔哩
      - 游戏平台
      - 微软服务
      - 苹果服务
      - 漏网之鱼
      - 日本节点
      - 狮城节点
      - 台湾节点
      - 香港节点
      - 其余节点

rule-anchor:
  classical: &classical
    type: http
    behavior: classical
    format: text
    interval: 86400
    proxy: 节点选择

  ip: &ip
    type: http
    behavior: ipcidr
    format: mrs
    interval: 86400
    proxy: 节点选择

  domain: &domain
    type: http
    behavior: domain
    format: mrs
    interval: 86400
    proxy: 节点选择

rule-providers:
  special_address:
    <<: *classical
    path: ./rule_providers/special_address.list
    url: "__SPECIAL_ADDRESS_URL__"

  custom_direct:
    <<: *classical
    path: ./rule_providers/custom_direct.list
    url: "__CUSTOM_DIRECT_URL__"
  custom_proxy:
    <<: *classical
    path: ./rule_providers/custom_proxy.list
    url: "__CUSTOM_PROXY_URL__"

  ads_domain:
    <<: *domain
    path: ./rule_providers/ads_domain.mrs
    url: "https://raw.githubusercontent.com/TG-Twilight/AWAvenue-Ads-Rule/main/Filters/AWAvenue-Ads-Rule-Clash.mrs"

  private_domain:
    <<: *domain
    path: ./rule_providers/private_domain.mrs
    url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/private.mrs"
  private_ip:
    <<: *ip
    path: ./rule_providers/private_ip.mrs
    url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/private.mrs"

  bilibili_domain:
    <<: *domain
    path: ./rule_providers/bilibili_domain.mrs
    url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/bilibili.mrs"
  bilibili_ip:
    <<: *ip
    path: ./rule_providers/bilibili_ip.mrs
    url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo-lite/geoip/bilibili.mrs"

  tiktok_domain:
    <<: *domain
    path: ./rule_providers/tiktok_domain.mrs
    url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/tiktok.mrs"

  steam_domain:
    <<: *domain
    path: ./rule_providers/steam_domain.mrs
    url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/steam.mrs"

  fcm_domain:
    <<: *domain
    path: ./rule_providers/fcm_domain.mrs
    url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/googlefcm.mrs"

  google_domain:
    <<: *domain
    path: ./rule_providers/google_domain.mrs
    url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/google.mrs"
  google_ip:
    <<: *ip
    path: ./rule_providers/google_ip.mrs
    url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/google.mrs"

  microsoft_domain:
    <<: *domain
    path: ./rule_providers/microsoft_domain.mrs
    url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/microsoft.mrs"

  apple_domain:
    <<: *domain
    path: ./rule_providers/apple_domain.mrs
    url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/apple.mrs"
  apple_ip:
    <<: *ip
    path: ./rule_providers/apple_ip.mrs
    url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo-lite/geoip/apple.mrs"

  porn_domain:
    <<: *domain
    path: ./rule_providers/porn_domain.mrs
    url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/category-porn.mrs"

  geolocation_not_cn:
    <<: *domain
    path: ./rule_providers/geolocation_not_cn.mrs
    url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/geolocation-!cn.mrs"
  cn_domain:
    <<: *domain
    path: ./rule_providers/cn_domain.mrs
    url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/cn.mrs"
  cn_ip:
    <<: *ip
    path: ./rule_providers/cn_ip.mrs
    url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/cn.mrs"

rules:
  - AND,((NETWORK,UDP),(DST-PORT,443),(NOT,((OR,((RULE-SET,cn_domain),(RULE-SET,cn_ip,no-resolve),(RULE-SET,private_domain),(RULE-SET,private_ip,no-resolve),(RULE-SET,custom_direct,no-resolve)))))),QUIC
  - RULE-SET,special_address,特殊地址,no-resolve
  - RULE-SET,custom_direct,DIRECT,no-resolve
  - RULE-SET,custom_proxy,节点选择,no-resolve
  - RULE-SET,ads_domain,广告拦截
  - RULE-SET,private_domain,DIRECT
  - RULE-SET,bilibili_domain,哔哩哔哩
  - RULE-SET,tiktok_domain,TikTok
  - RULE-SET,steam_domain,游戏平台
  - RULE-SET,fcm_domain,谷歌FCM
  - RULE-SET,google_domain,Google
  - DOMAIN-SUFFIX,dl.delivery.mp.microsoft.com,DIRECT
  - DOMAIN-SUFFIX,windowsupdate.com,DIRECT
  - RULE-SET,microsoft_domain,微软服务
  - RULE-SET,apple_domain,苹果服务
  - RULE-SET,porn_domain,PORN
  - RULE-SET,geolocation_not_cn,节点选择
  - RULE-SET,cn_domain,DIRECT

  - RULE-SET,private_ip,DIRECT
  - RULE-SET,bilibili_ip,哔哩哔哩
  - RULE-SET,google_ip,Google
  - RULE-SET,apple_ip,苹果服务
  - RULE-SET,cn_ip,DIRECT
  - MATCH,漏网之鱼
